name: EC2 Auto Deploy

on:
  push:
    branches: [ "master" ]  # main 브랜치에 push 될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/SpringBoot_DashBoard_Project
          git pull origin master
          docker stop spring-app || true
          docker rm spring-app || true
          docker build -t my-spring-app .
          docker run --name spring-app --restart=always -d -p 8080:8080 my-spring-app
        EOF
